### ISSUE TITLE
If activeWorker’s list of foreign fetch origins is empty, should set originMatches to false

### ISSUE THREAD

**Issue by leonhsl** [w3c/ServiceWorker#1112]
About step 11 in https://w3c.github.io/ServiceWorker/#on-foreign-fetch-request-algorithm, 
"11. If activeWorker’s list of foreign fetch origins is empty, set originMatches to true."

Should we set originMatches to false instead?

**Comment by mkruisselbrink** [comment]
No, I believe "true" is the right value. If the list of foreign fetch origins is empty that means that "*" was passed as origins to registerForeignFetch, and as such any origin should match the foreign fetch registration (admittedly using "empty list" to mean all origins is a bit confusing, but since empty list otherwise isn't a valid value anyway, it seemed like the easiest thing to do).
