### ISSUE TITLE
Service Worker registration failed:  DOMException: Failed to register a ServiceWorker: An SSL certificate error occurred when fetching the script.

### ISSUE THREAD

**Issue by GandhasiriSandeep** [w3c/ServiceWorker#1159]
I am getting this error when i am running in my local system. I am working with service worker.

Service Worker registration failed:  DOMException: Failed to register a ServiceWorker: An SSL certificate error occurred when fetching the script.
What is the solution. help me

**Comment by jakearchibald** [comment]
Hi, this repo is for spec issues rather than user support. I recommend https://stackoverflow.com/ for user support, and if you post your question there, post me a link, I'll attempt to answer it.

However, you need to provide as much information as possible, and you haven't provided any code, or information about the environment.

You may also be interested in https://www.chromium.org/blink/serviceworker/service-worker-faq which covers solutions for some self-signed certificates.

**Comment by NevilDabre** [comment]
If Anyone still looking for a solution - https://deanhume.com/testing-service-workers-locally-with-self-signed-certificates/

**Comment by pinobatch** [comment]
@jakearchibald The question was asked on Stack Overflow: ["Can you use a service worker with a self-signed certificate?" by Keith](https://stackoverflow.com/q/38728176/2738262)

**Comment by Reddy2324** [comment]
@ https://apps.apple.com/us/app/overcast/id888422857

**Comment by Reddy2324** [comment]
#[https://apps.apple.com/us/app/overcast/id888422857](https://apps.apple.com/us/app/overcast/id888422857)

**Comment by Reddy2324** [comment]
@GandhasiriSandeep
