### ISSUE TITLE
Job queue items may not have a service worker registration

### ISSUE THREAD

**Issue by jakearchibald** [w3c/ServiceWorker#1180]
There's a separate [job queue](https://w3c.github.io/ServiceWorker/#dfn-job-queue) for each service worker registration, but during the initial call to `serviceWorker.register()` that registration does not exist, yet a job is queued in [Start Register](https://w3c.github.io/ServiceWorker/#start-register-algorithm).

If there are two initial calls to register for the same scope in different processes, we want to ensure they queue.

@jungkees what do you think? Seems like we can safely remove the reference to the registration in the [job queue](https://w3c.github.io/ServiceWorker/#dfn-job-queue), and use scope url as the key.

Thanks to @beidson for spotting this!

**Comment by wanderview** [comment]
This section does say "keyed by its scope url":

https://w3c.github.io/ServiceWorker/#dfn-job-queue

But it is a bit hand wavy about when the queue is created, etc.

**Comment by jakearchibald** [comment]
We should probably add "job queues", an [ordered map](https://infra.spec.whatwg.org/#maps) where scope is the key.

**Comment by wanderview** [comment]
That is effectively what we have, although our implementation is more like:

top level -> map from origin to "per-origin data" -> map from scope to job queue

We have the map from origin first because of things like double-keying, firefox "containers", etc that extend the origin with more uniqueness attributes.

**Comment by jakearchibald** [comment]
I guess we only need double-keying for foreign fetch.

**Comment by wanderview** [comment]
> I guess we only need double-keying for foreign fetch.

No, I think it affects everything here.  If you create a unique origin in some way (like double-keying) then it needs to have separate storage which means separate SW registrations, etc.

Of course, AFAIK double-keying is not spec'd.  So all of this is an implementation detail.  A per-origin map keyed on scope is enough for now.

**Comment by jakearchibald** [comment]
Ahh good point, if an iframe registers a service worker, you get double keying.

**Comment by wanderview** [comment]
BTW, why does the map need to be ordered?

**Comment by jakearchibald** [comment]
It doesn't, but infra doesn't seem to provide an unordered map.

**Comment by jungkees** [comment]
The current spec text
> A user agent must maintain a separate job queue for each service worker registration keyed by its scope url.

didn't mean to say a job queue is owned by a service worker registration.

But I agree it'd clarify it if we introduced a scope-to-job-queue map rather than kept a prose like the above. And that's also what browsers implemented already.

Re: the creation time of a map, I think we can just say a user agent has a scope-to-job-queue map though. It seems Chromium creates one when a ServiceWorkerContextCore is created, and Gecko creates one lazily (GetOrCreate style)  when the first register job is triggered. I think it depends on implementations.

> A per-origin map keyed on scope is enough for now.

I understand what Gecko implemented. But I don't think we need to explicitly say it's *per-origin* map. Just *scope-to-job-queue map* should be fine, right?

> unordered map.

I think we can spec that in infra if it's needed. But I don't think we should specify it should be ordered or unordered. Chromium current uses std::map for example. I guess an unordered_map seems a better fit though.

**Comment by jungkees** [comment]
> If there are two initial calls to register for the same scope in different processes, we want to ensure they queue.

Actually, the second register for the same scope should be squashed (aggregated) to the first one.

**Comment by jakearchibald** [comment]
> Just scope-to-job-queue map should be fine, right?

Yeah I think that's fine. We can revisit it if double-keying makes it into any spec.
