### ISSUE TITLE
Why is the scope to registration map and ordered map?

### ISSUE THREAD

**Issue by cdumez** [w3c/ServiceWorker#1225]
Why is the scope to registration map and ordered map?

See https://w3c.github.io/ServiceWorker/#dfn-scope-to-registration-map.

This ordered is exposed via getRegistrations() but I do not know that the insertion order is useful. Keeping such order has a cost so I'd like to understand why it is mandated by the specification.

**Comment by cdumez** [comment]
The order is covered by WPT (see https://github.com/w3c/web-platform-tests/pull/8180).

**Comment by cdumez** [comment]
cc @beidson & @youennf

**Comment by mkruisselbrink** [comment]
Yeah, the notes in the infra spec around ordered maps/sets probably apply here (i.e. the right question to try to answer isn't "why is it an ordered map", but instead "why shouldn't it be an ordered map"):

"Almost all cases on the web platform require an ordered set, instead of an unordered one, since interoperability requires that any developer-exposed enumeration of the set’s contents be consistent between browsers. In those cases where order is not important, we still use ordered sets; implementations can optimize based on the fact that the order is not observable."
