### ISSUE TITLE
Should the fragment identifier be stripped from the scriptURL?

### ISSUE THREAD

**Issue by cdumez** [w3c/ServiceWorker#1249]
Should the fragment identifier be stripped from the scriptURL? I cannot find any indication that we should in the specification. However, Firefox and Chrome seem to do so and it is tested via:
- service-workers/service-worker/serviceworkerobject-scripturl.https.html

**Comment by cdumez** [comment]
cc @beidson

**Comment by bsittler** [comment]
See https://github.com/w3c/ServiceWorker/issues/742

**Comment by cdumez** [comment]
#742 was closed in 2015 and it seems Firefox and Chrome still have not aligned with the specification.
Also, there is disagreement between web-platform-tests and the specification.

**Comment by cdumez** [comment]
cc @jungkees

**Comment by jungkees** [comment]
Good catch! The spec and the test don't agree now. I'm happy to change the spec if the existing implementations agree on not storing fragments. If so, I presume it wouldn't break things much, right? Also, that behavior aligns to what we do for storing scope urls. @aliams, could you confirm if it'd be okay for Edge too?

/cc @jakearchibald @wanderview @mattto

**Comment by jungkees** [comment]
I tested with Edge and confirmed it doesn't return fragments either.

**Comment by docluv** [comment]
Are the hash fragments not stored as part of the request URL?

And would the fragment even make it to the service worker since that part of the URL would not be sent to the server? They are really to drive client-side behavior and not network/server behavior.
If a fragment was used it is retained in the client-side to drive the desired behavior, but would not initiate a network request, assuming the base url did not change.

**Comment by jungkees** [comment]
For service workers' script urls and scope urls, we intend to not store the fragments in the internal spec structs by this change. Please note that we don't remove the fragments of the request URLs in the use of the Cache API though.
