### ISSUE TITLE
Is resultingClientId preserved over redirects?

### ISSUE THREAD

**Issue by mattto** [w3c/ServiceWorker#1316]
Splitting off of https://github.com/w3c/ServiceWorker/pull/1315

On my reading of the spec, I thought the reserved client gets set one time at the beginning of a navigation, and it never changes until navigation finishes.

In the Chrome we were just going to not give reserved clients URLs (or rather, we'd essentially ignore whatever URL it currently has until navigation settles). But we would preserve resultingClientId over cross-origin redirects. I believe a team here wanted this at least for same-origin redirects but probably don't care about cross-origin. Is there any reason we'd prefer to preserve or discard the id for cross-origin ones?

**Comment by annevk** [comment]
Currently https://html.spec.whatwg.org/#process-a-navigate-fetch ends up resetting the reserved client for each redirect.

When and where is the reserved client exposed? It seems bad if different origins can get hold of the same unique identifier, so if you're proposing changing the above setup to not reset it for each redirect, we should make sure that's not possible.

**Comment by mattto** [comment]
Reserved clients are never exposed. Clients.get(id) resolves once the navigation finishes or rejects once the navigation failed. It would also reject if the resulting client is cross-origin to the caller. So I was thinking just having the same unique identifier would be safe.

In #process-a-navigate-fetch, I thought the relevant part (navigation follows a redirect) is step 7:
"If response has a location URL and it is either failure or a URL whose scheme is an HTTP(S) scheme, then set response to the result of performing HTTP-redirect fetch using request and response and then run this step again."

I read that as running step 7 again, i.e., step 5 only happens once.

**Comment by annevk** [comment]
You're reading that correctly, I was mistaken. That means the URL never gets updated though. It also means the CSP check only gets applied once. That's almost certainly a bug.

**Comment by wanderview** [comment]
I believe we agreed at a previous f2f to reset the resulting client when we perform a cross-origin redirect.  Because clients are tied to their origin, something like this must happen.  Otherwise we risk exposing the same client ID to two different origin service workers.

For example, a fetch event for origin A, then a redirect to origin B, and then a fetch event on origin B.  The origin A and origin B should see different client IDs, IMO.

I'll look later today to try to find where we discussed that before.

**Comment by wanderview** [comment]
Please see https://github.com/w3c/ServiceWorker/issues/1031#issuecomment-291056646.

**Comment by wanderview** [comment]
@jakearchibald In https://github.com/w3c/ServiceWorker/issues/1031#issuecomment-346641083, were you just bulk closing "reserved client" issues or were you saying you think we should reverse the previous f2f issue?

**Comment by mattto** [comment]
I think having the same ID helps them connect the two fetch events together in their logging, so they know the events were part of the same navigation. They can probably do some manual work to accomplish the same but it'd be less convenient.

I'll loop back to them.

Sorry that this would amount to a huge change here and sorry I didn't acknowledge that earlier in the thread. I thought the earlier discussions were more complicated because we planned to expose reserved Clients to JavaScript. When we decided to not expose them, a lot of the problems went away, and I thought sharing an ID would be harmless if the cross-origin can't get a Client out of the ID (and I thought the spec was saying to preserve the IDs, but as I learned here that wasn't intended).

**Comment by wanderview** [comment]
I'm not sure I really want to do this either, but we could try to preserve the original client and use it again after the redirect back to the original origin.  So the answer to the question in https://github.com/w3c/ServiceWorker/issues/1031#issuecomment-278528042 would be two clients instead of the previously agreed four clients.

My main concern here is that it could get complicated with long redirect chains.  We could end up trying to preserve and track up to 19 different origin clients in case that last redirect goes back to one of them.

**Comment by mattto** [comment]
Fixed by https://github.com/whatwg/html/commit/45ddbd291d1ccd6feab734f6bcd7e222dc7d770e

Preserved on same-origin redirects, changed on cross-origin redirects.
