### ISSUE TITLE
Allow active service worker to manage fetch for the update logic

### ISSUE THREAD

**Issue by roosmaa** [w3c/ServiceWorker#1318]
Currently the service worker [update algorithm](https://w3c.github.io/ServiceWorker/#update-algorithm) specifies that the _request_’s _service-workers mode_ should be set to "none", which prevents the currently active service worker from intercepting this request (if I understand the specs correctly). I tried finding the reason behind that decision, but couldn't find any discussions around that. So I'm guessing this is mostly to prevent people from accidentally shooting themselves into the foot and creating a service worker that caches itself forever.

I would like to propose that there should be a way to force the update algorithm to route its requests through the currently active service worker.

Having such an option would allow security critical websites to use the service worker to implement public-key digital signature verification for data/code that is downloaded. It would be a way to protect against compromised CDN, DNS servers and BGP hijacking.

**Comment by jakearchibald** [comment]
> So I'm guessing this is mostly to prevent people from accidentally shooting themselves into the foot and creating a service worker that caches itself forever.

Correct. It's also essential for security. Imagine a site was compromised, and an attacker was able to install an evil service worker. Once the site is back in control of the owner, they need to be able to deploy a fixed service worker, which should probably clear site storage.

Because of this, the service worker shouldn't be able to prevent updates.
