### ISSUE TITLE
Service worker not intercepting the call intiated for CSS from JS files “ css:”css/custom.css"

### ISSUE THREAD

**Issue by ajeeshc** [w3c/ServiceWorker#1386]
0

I have implemented an application with CK editor with Few additional plugin (LITE - Track Changes, Formatted, Color picker and i implemented service worker to make the application offline.

When i took offline the application is able to open and no CSS which called by the plugin is not available in the offline mode. when i debugged these CSS which getting called from the JS file of the plugin inside CK editor are not getting intercepted in the fetch event.

Approch1 : i manually load all the CSS that getting called from the [plugin.js] and all getting fetched by the service worker and able to cache [ Cache first approach]. Still when the application goes offline these are not getting retrieved from Cache API because these call not getting in fetch even
![zytsq](https://user-images.githubusercontent.com/3844100/51863939-5c824180-2310-11e9-97f7-5a05cbd19cb9.png)

If you see the network call only the CSS which i added in page load getting cached and even with same url the next call not getting fetched from Cache API. [ 5 calls going because i put 5 CKD in my screen and initiated separately ] 
![fh6nt](https://user-images.githubusercontent.com/3844100/51863973-70c63e80-2310-11e9-9c4e-1c76adb304d9.png)

Any thread to dig on this will be realy help full.

**Comment by wanderview** [comment]
Sorry, but this repo is for discussing the service worker specification.  Its not really for this kind of support style question.

If you can reduce your test case to a small reproduction of the issue then I recommend filing a bug on the browser where you see the unexpected behavior.  This looks like chrome devtools so that would be here:

https://bugs.chromium.org/p/chromium/issues/entry

For more general questions the service worker section on stack overflow may be helpful.  But I see you actually just asked a question there:

https://stackoverflow.com/questions/54424726/any-call-from-inside-a-iframe-note-fetch-by-service-worker-ck-editor

Is this the same problem?  If so, its because the document.open() is creating an about:blank document which is not yet controlled by the parent's service worker in chrome.  The relevant bug for that issue is here:

https://bugs.chromium.org/p/chromium/issues/detail?id=880768

Hope that helps.
