### ISSUE TITLE
Missing task queuing

### ISSUE THREAD

**Issue by Ms2ger** [w3c/ServiceWorker#1403]
In https://w3c.github.io/ServiceWorker/#run-service-worker-algorithm , step 4.13 says

> If callbackSteps is provided, run them with evaluationStatus on the original thread that invoked this algorithm, while continuing in parallel with these steps.

That's not really something that can work. Anne suggests queuing a task instead.

**Comment by mkruisselbrink** [comment]
It's not entirely clear to me why that can't work? It sort of reads to me like the calling thread is supposed to be "blocked" while steps 4.1 - 4.12 are executed. Only after 4.13 is there a "continue in parallel", so before that everything is just sequenced?

**Comment by annevk** [comment]
How can you run something on the original thread without scheduling that run in some way?

**Comment by mkruisselbrink** [comment]
The way I read it the original thread is just waiting around when we reach step 4, until that reaches step 4.13. So there is nothing to schedule, since the thread is just waiting.

But I do agree that this does seem unclear. Also "Run Service Worker" isn't consistently used the same way. Definitely for the cases where Run Service Worker is invoked synchronously from idl methods, as for example in post message, blocking the calling thread until the worker script has been evaluated doesn't make sense, so at least for those cases (ones where no callback steps are passed in to run service worker) my interpretation doesn't make sense.

And since afaict callback steps actually only seemed to be used in one place (in the Update algorithm), some kind of scheduling probably makes sense. But I'm not sure what task queue tasks would get posted to. It's not like the "update" algorithm is running on any particular task queue (actually I have no idea where the "Run Job" algorithm is posting tasks to. All these tasks really aren't associated with any particular agent, but afaict event loops are always associated to agents?

**Comment by annevk** [comment]
Using HTML's parallel queue might make sense in such cases.

But also, HTML creates these kind of threads in parallel, not synchronously from, e.g., `postMessage()`. That seems wrongish?

**Comment by mattto** [comment]
Yes my intent was that Update would block until the callback is run with the result of starting the service worker.

For postMessage(), doesn't it still make sense to wait for the service worker to have started before continuing? I.e., the service worker's global object must be set for the postMessage() steps to work.

I'm guessing we want Run Service Worker to block until the service worker starts (just before "Run the responsible event loop" is called) and return the evaluation status. Is there a rigorous way to specify that?

Something like:

Run Service Worker:

3. Let `evaluationStatus` be null.
4. Create a separate parallel execution environment (i.e. a separate thread or process or equivalent construct), and run the following substeps in that context in parallel:
4.1. Setup the service worker...
 ...
4.14. Set `evaluationStatus` to status.
4.15. Run the responsible event loop...
5. Wait for `evaluationStatus` to be set.
6. Return `evaluationStatus`.

**Comment by annevk** [comment]
It would make sense to if `postMessage()` started an algorithm in parallel to start the service worker, but making that block the thread `postMessage()` was invoked in doesn't seem desirable.

**Comment by mattto** [comment]
Thanks all. Addressed in https://github.com/w3c/ServiceWorker/pull/1419
