### ISSUE TITLE
The requested service worker becomes redundant and a new and random service worker gets reqeusted and registered

### ISSUE THREAD

**Issue by rishabhnigamoyo** [w3c/ServiceWorker#1479]
Hi , I am using service worker in my website and it is showing unexpected behaviour.
I have the following code 

`window.addEventListener('load', function(){
  navigator.serviceWorker.register("/service-worker-mobile.js",{scope: "/"});
  });`
Now, service-worker-mobile.js is fetched and starts to register but then becomes redundant and a new service worker( which I am not requesting anywhere in my code) gets requested as "service-worker.js".

To tackle this problem , I created routing for "/service-worker.js" to rewrite it to "/service-worker-mobile.js" in a virtual host context in NGINX configuration.

I am not able to figure out, why this service-worker.js is being requested.

Any help would be appreciated and thanks in advance.

**Comment by jakearchibald** [comment]
Closing, because this isn't a spec issue, but I'll continue to provide support.

Chrome's dev tools (particularly the application tab) will tell you about errors during service worker execution. It'll also tell you if there's more than one registration going on.

I suspect there's an additional service worker registration on your site, but it's difficult to tell without further details. Use [`navigator.serviceWorker.getRegistrations`](https://w3c.github.io/ServiceWorker/#navigator-service-worker-getRegistrations) to see if there are other registrations.

**Comment by rishabhnigamoyo** [comment]
Hi , you can check it on our website 'https://www.oyorooms.com'. Both in mobile mode and desktop mode, the same behaviour is being happened. 
I am adding screenshot for reference
<img width="1435" alt="Screen Shot 2019-10-11 at 5 44 26 PM" src="https://user-images.githubusercontent.com/46915741/66650701-e11eb100-ec4e-11e9-8ff7-e7c0db9f8ea6.png">

Here  we only request service-worker-mobile.js and not service-worker.js. 
The code where we request for service worker can be seen in View Page Source: of https://oyorooms.com

Please look into this once.
thanks

**Comment by rishabhnigamoyo** [comment]
Hi , please look into this and open this issue.
thanks in advance.
