### ISSUE TITLE
Should we consider Worklets as clients?

### ISSUE THREAD

**Issue by bakulf** [w3c/ServiceWorker#1502]
At the moment, the ClientType values are  "window", "worker", "sharedworker", "all".
I would like to know how we should consider Worklets.

Worklet specs:
https://drafts.css-houdini.org/worklets/#worklet
https://webaudio.github.io/web-audio-api/#audioworklet

**Comment by nhiroki** [comment]
Conceptually worklets could be service worker clients, but it doesn't make much sense because worklets have opaque origins and cannot be visible to Client API.

```
3. Let origin be a unique opaque origin.
https://drafts.css-houdini.org/worklets/#script-settings-for-worklets
```

In addition to that, worklets don't have networking APIs including dynamic ```import()``` and Event mechanism (except for AudioWorklet's MessageEvent), so service workers cannot communicate with them.

```
Are not event API based. Instead classes are registered on the global scope, whose methods are to be invoked by the user agent.
https://drafts.css-houdini.org/worklets/#motivations
```

Note that worklet module script graph is fetched like the owner document's subresource request, so it can be intercepted by the owner document's active service worker.

Relevant issue: w3c/css-houdini-drafts#473

**Comment by wanderview** [comment]
Right, I don't have the previous discussion link handy, but I recall we conceded to make worklet requests subresource requests since they are opaque and not visible to service workers.

**Comment by annevk** [comment]
Let's dupe this into https://github.com/w3c/css-houdini-drafts/issues/473, but I suspect the answer is no.
