### ISSUE TITLE
Check if <script>'s fetch request has an integrity attribute

### ISSUE THREAD

**Issue by guanzo** [w3c/ServiceWorker#1507]
Imagine a service worker that intercepts requests for js files, sends it to a js optimization service, then returns the optimized response (Disregard the fact that this would be really slow). If the script tag that spawned this request has the `integrity` attribute, the response would be rejected, right? Because the hash of the optimized js would differ from the original js.

The `integrity` property in the fetch event always seems to be an empty string. Is there a way to know if a <script>'s fetch request has an integrity attribute?

**Comment by wanderview** [comment]
This is a browser bug, not a spec bug.  If you go to:

https://fetch-event-echo.glitch.me/

Open the console and reload you will see the FetchEvent contents echoed.  (You may need to open in a new tab to see the script FetchEvent in chrome due to memory cache.)  The jquery script tag has integrity information on it.

In firefox the FetchEvent.request.integrity field is populated.  In chrome it is not.  This is covered by WPT and is filed against chrome at:

https://bugs.chromium.org/p/chromium/issues/detail?id=850825
