### ISSUE TITLE
[question]: how do CacheStorage save encoded responses?

### ISSUE THREAD

**Issue by jimmywarting** [w3c/ServiceWorker#1641]
is it up to the browser how they store the response? or is it some spec that says that it should unpack it?

if i put a `Request` into the browsers CacheStorage and that `Response` respond with a `content-encoded: gzip` or brotli encoded response, dose it store it as encoded or will it unpack the response and then store it?

I want to know how this effects the quota on browser storage...

**Comment by wanderview** [comment]
Response.body data is required to be decoded.  There is no requirement for how browsers store the data, however.  For example, firefox compresses cache_storage bodies using snappy.  In chromium the bodies are stored uncompressed.  (I don't know what webkit does.)

**Comment by wanderview** [comment]
And to clarify, there are tradeoffs between compressing and not compressing.  Compressing saves space on disk but can make certain operations that require seeking within the body data more expensive at runtime.

**Comment by jimmywarting** [comment]
hmm, i tried this in devtool on some random webpages, both in chrome and firefox on mac
```js
c = await caches.open('x')
await c.add('/');
(await navigator.storage.estimate()).usage
```

seems like chrome save you some more data.
safari don't have `estimate()`

**Comment by wanderview** [comment]
Correct.  That's consistent with what I wrote above.  Firefox compresses on disk and chrome does not, so chrome disk usage will be higher.

**Comment by jimmywarting** [comment]
I found that the disk usage was higher on firefox

**Comment by wanderview** [comment]
If you are storing only one resource you may be measuring database overhead.  Anyway, on-disk representation is not spec'd.

**Comment by jimmywarting** [comment]
hmm, ok... thanks anyway. think i got my answer

**Comment by asutherland** [comment]
I should note that during discussions related to how to quota track Blobs/Files in multiple storage buckets and potentially applying limits to structured serialization payloads, we've been moving towards standardizing quota usage so that the accounting is deterministic and predictable from the data put in and decoupled from the on-disk representation, including any browser optimizations.

As an example, right now Firefox has a number of optimizations so that if you put() a Blob/File into a db multiple times, only a single copy of the blob is stored and a refcount tracks the number of uses of that blob.  The net effect is the blob's size is only charged once even if stored N times.  If we undertake a change like that, the blob would be charged all N times.  This would be beneficial in terms of avoiding potential side-channel information leaks and improving cross-browser web-compat.  Browsers could leverage implementation savings by being more generous with quota, ideally in a way that exposes limited side channel information.
