### ISSUE TITLE
Feedback on the ServiceWorker feature in the web-platform-dx/web-features project

### ISSUE THREAD

**Issue by autonome** [w3c/ServiceWorker#1738]
Hello! I'm a contributor to the Web Features project, which is an initiative of the W3C Web DX CG.

Web Features groups the 15k+ individual [keys](https://github.com/mdn/browser-compat-data/) in the web platform into a smaller logical set of "features" that align with the developer point of view of the web.

These features will be used by [MDN](https://developer.mozilla.org/), [Caniuse](https://caniuse.com/) and more.

More information on this project is here: https://web-platform-dx.github.io/web-features/

We've drafted a "feature" for ServiceWorker here: https://github.com/web-platform-dx/web-features/pull/2357

If someone here has feedback on any of the following, we appreciate it. If not, carry on and close this!

- Does this feature grouping align with your understanding of how developers think about ServiceWorkers?
- Are there components that should *not* be bundled with main ServiceWorker feature? If so, why?
- Any feedback on the name and description of the feature?
- Anything else we should know?

Thank you!

**Comment by mkruisselbrink** [comment]
Not sure how to read that pull request, but I would definitely not group the "Caches" API with the rest of service workers. While it was designed to be convenient to be used in conjunction with service worker fetch events nothing about it limits it to that use case, and really the only reason it's in the same spec is because nobody has done the work to split it off, not because it logically belongs here (i.e. see https://github.com/w3c/ServiceWorker/issues/879).

**Comment by autonome** [comment]
That's very helpful input, thanks @mkruisselbrink!
