### ISSUE TITLE
Make ExtendableEvent#waitUntil generic

### ISSUE THREAD

**Issue by jakearchibald** [w3c/ServiceWorker#554]
It's almost there, just needs specific references to install/activate removed

**Comment by mvano** [comment]
The current spec attaches very little meaning to calling waitUntil for events other than the `install` and `activate` events. The only meaning seems to be that the promises are added to `extend lifetime promises`. Can we have some additional text that says something along the lines of:

"The Service Worker should not be terminated until the `extend lifetime promises` have been settled. However, a time limit may be applied to this lifetime in order to kill endless loops and similar bad code."

It would be phrased differently in the spec, but hopefully you get the gist of it.

**Comment by jungkees** [comment]
Added text for that: 7c530ba152d2ea57bae4197855d113863c7828c8. Thanks!

**Comment by mvano** [comment]
Thanks!

**Comment by johnmellor** [comment]
Thanks @jungkees ! One nit: "infinite loops and similar defective code" is quite specific, and doesn't seem to cover the case where the Service Worker JS is deliberately (non-defectively) performing a long sequence of asynchronous tasks, e.g. video encoding or bitcoin mining, where the work has been split into small asynchronous chunks. Especially on mobile, UAs cannot guarantee that the SW will stay alive for very long, and hence they may wish to impose execution time limits in this case also.

**Comment by jungkees** [comment]
Good point. How about "... the user agent may impose a time limit to this lifetime extension in order to abort abnormal operation such as infinite loops, the execution of tasks exceeding the time limit and so forth."? or even drop the such as phrase entirely?

**Comment by johnmellor** [comment]
That looks perfect - thanks!
