### ISSUE TITLE
Create service worker from Blob/String URL

### ISSUE THREAD

**Issue by h2non** [w3c/ServiceWorker#578]
I guess it's a security decision, however it could be really useful for better and easier approach when developing generic libraries which needs to abstract implementation details to end developers which uses the ServiceWorker to provide functionalities such as transpartent assets caching or HTTP traffic interceptor/modification on the flight

Taking a look to its parent implementations (Workers and SharedWorkers), any developer can create them using different ways to dynamically serialize code and transforming it as a binary. I think that the same feature for service workers will be great match. The scope limitation has no sense in this cases

A basic example:

``` js
var workerBlob = new Blob([ serviceWorkerFn.toString() ], { type: 'text/javascript' })
navigator.serviceWorker.register(URL.createObjectURL(workerBlob))
  .then(function () { ... })
  .catch(function () { ... })
```

**Comment by jdalton** [comment]
Is there something specific about `Blob` use that makes it worse than other options? If there is  a successful attack on a server and files are compromised would that trump this guard?

**Comment by jakearchibald** [comment]
If it allows a SW to be registered in a way that prevents the owner of the controlled origin from unregistering it, we don't want it 😀

**Comment by jdalton** [comment]
If a server is compromised though they could register a service worker in the traditional way since they have access to files. Is this less about compromised servers and more about XSS guards?

**Comment by jdalton** [comment]
Ah I see to unregister you need a url to act as a key. Gotcha.

**Comment by jdalton** [comment]
Hmm actually unregistering doesn't require a key so That doesn't resolve the issue.

**Comment by mkruisselbrink** [comment]
The problem is that to unregister you need to first actually get to get code to run on that origin. If the service worker doesn't have an actual network url to check for updates, the service worker can just intercept all navigation, and never let any new request to the server actually reach the server, so even fixing the server won't enable fixing the clients. Basically the entire 24 hour update check wouldn't be possible anymore with blob urls.

**Comment by inian** [comment]
It could lead to faster SW startup times since there is not RTT involved in fetching the scripts..Might make sense for SW scripts that are small enough to be inlined..

**Comment by wanderview** [comment]
What @mkruisselbrink said.

>It could lead to faster SW startup times since there is not RTT involved in fetching the scripts..Might make sense for SW scripts that are small enough to be inlined..

We've tried to design things so the install of a service worker does not block page load or interactivity.  So optimizing install and update times will not have much visible effect for the user.  I think we should err towards correctness and safety for these cases.

**Comment by qm3ster** [comment]
I found a usecase :rofl: 
Incremental updates to the serviceworker.
If the serviceworker is over a gorillion gibibytes, the server could generate a diff from a known past version and send that.

(Yes, I know what `WorkerGlobalScope.importScripts()` is)

**Comment by Zibri** [comment]
It would be way better for web-apps and single file contained local apps.
Also since serviceworkers are used in push notifications this will allow to receive push notifications from a local hosted app.

**Comment by goofballLogic** [comment]
> We don't want to support this because it would mean a single successful attack on a server could compromise users for a long time.

@annevk is there anywhere there is more reading on this topic? I'm eager to learn more

**Comment by jakearchibald** [comment]
@goofballLogic https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle

The browser needs to know where it should look to discover service worker updates.

**Comment by Hashbrown777** [comment]
> It could lead to faster SW startup times since there is not RTT involved in fetching the scripts..Might make sense for SW scripts that are small enough to be inlined..

Possibly better to multiplex the SW script into requests for the script containing the `navigator.serviceWorker.register()` call using HTTP2.0.

**Comment by jikkujose** [comment]
But isn't there a way other than Blob URL to inline the service worker in a single HTML page so a fully contained page can be a valid PWA?

**Comment by benkaiser** [comment]
@annevk could a potential mitigation against the "single attack compromising users for a long time" issue be to only persist the service worker for the current session?

The use case I have for this is quite odd. I'm trying to register a service worker from a chrome extension so that I can get a PWA install prompt to show up. Basically building a chrome extension that lets you convert any website into a PWA.

**Comment by alimertcakar** [comment]
> @annevk could a potential mitigation against the "single attack compromising users for a long time" issue be to only persist the service worker for the current session?
> 
> The use case I have for this is quite odd. I'm trying to register a service worker from a chrome extension so that I can get a PWA install prompt to show up. Basically building a chrome extension that lets you convert any website into a PWA.

yeah we are trying to do the same thing. can't find a way around. only if chrome let us make any site into a pwa itself...

**Comment by nin-jin** [comment]
> The problem is that to unregister you need to first actually get to get code to run on that origin. If the service worker doesn't have an actual network url to check for updates, the service worker can just intercept all navigation, and never let any new request to the server actually reach the server, so even fixing the server won't enable fixing the clients. Basically the entire 24 hour update check wouldn't be possible anymore with blob urls.

But this is exactly what is needed to protect against server compromise. The current serviceworker downloads a new one, checks its digital signature and only then initiates an update.

**Comment by Sean4572435243** [comment]
The idea that potentially numerous nefarious browser extensions can and are allowed to rewrite entire DOMs, and yet developers are inhibited from compiling efficient single-file websites due to some edge case of a web server being compromised, seems a conflict in philosophy about who bears the responsibility for mitigating an infected client, and seems overtly oppressive given that other mechanisms can be employed to achieve the objective of code integrity.

**Comment by hazae41** [comment]
There is more probability in being infected by the server in the long run if things are mutable

An immutable service worker implies an immutable webapp if cached properly

This would annihilate any possibility of server-side attack once first downloaded

Also if your webapp is infected (via XSS or supply-chain), it's probably already game over

Just let the developer choose between mutable and immutable service workers

The developer is probably the best person to evaluate such risk-benefit

**Comment by corrideat** [comment]
It's unfortunate that this is closed because, as it stands, there is no way to fully provide integrity protection to a PWA in the event of server compromise or takeover. This puts PWAs on unequal footing with native apps, which do have the ability _not_ to be updated, or to validate updates as much or as little as they wish.

In fact, if we were talking about a native application which would fetch updates from some endpoint and install them without verification, it'd be considered a glaring security issue.

On the other hand, I understand the concern that implementing this can:

  1. Lock the site owner from the site (accidentally or not), including updating it, and
  2. "A single successful attack on a server could compromise users for a long time"
  
I believe that both of these concerns can be addressed by:

  1. Adding "immutable" service workers. They don't necessarily have to be created using `data:` URLs, a flag would do.
  2. To alleviate XSS attacks, immutable service workers could be validated by some other mechanism, such as a special header with a script hash, or by fetching some well-known URL using a script hash.
  3. To alleviate other attacks, an explicit permission would be requested (and granted) for these types of service workers.
  4. It could even be possible to continuously check for updates, with the difference being that, if there's an update, the user would be warned and, if they proceed, site data would be cleared. This solves the "could compromise users for a long time" part.

**Comment by nin-jin** [comment]
> We don't want to support this because it would mean a single successful attack on a server could compromise users for a long time.

It may not be obvious to everyone, but the developer's private keys, which are used to sign updates, are not stored on the server. Therefore, in order to carry out such an attack, it is necessary to hack not only the server, but also to gain physical access to the private key storage, which most likely will not be connected to the Internet at all.

**Comment by anonghuser** [comment]
Even though this was closed, I'll still add my use-case for people that wonder why someone might want this:

I want to be able to create a service worker for some site in my tampermonkey userscripts. To alleviate your security concerns, it does not need to be as permanent as current service workers are - it should only affect the documents/tabs that explicitly register it, not all other tabs of the target domain. As such I accept the necessary drawback that it will never capture the initial load/reload of documents, direct downloads or image/video/audio media opened in a tab of its own, etc.

Sharing a single service worker of this type across tabs would still be good to have when they both register the same blob or data url, so bonus points if the blob url can be kept alive as long as other tabs still refer to it even after the tab that created it was closed. But if that's too complicated I'll be fine with a simpler implementation treating it as an entirely separate service worker instance with instantly outdated and thus never reused registration, and I will find a way to implement my shared functionality needs through a separate SharedWorker or other cross-tab messaging.

For the moment this use-case can be vaguely approximated by monkeypatching fetch and xhr and giving up on intercepting media requests, which often defeats the purpose of wanting the simple single universal request interception API of service workers, or by having userscript extensions like tampermonkey expose the extension webRequest api in some form which is very clunky, much harder to write for and ultimately often implemented as not flexible/dynamic enough again because of "security" (which should not be anyone's concern for my own user scripts on my own browser imo, but thats a whole different topic).

**Comment by hazae41** [comment]
Just let people do things ffs
