### ISSUE TITLE
Add option to ignore case for cache querying

### ISSUE THREAD

**Issue by aliams** [w3c/ServiceWorker#956]
As a convenience for web developers, we should add an option to make querying from the cache case insensitive. Perhaps we should add an `ignoreCase` option in `CacheQueryOptions`?

**Comment by asutherland** [comment]
Is the use-case for this web servers which are not (or whose backing file systems are not) case sensitive?  If so, it would be great to know if their behavior is consistent with a single hard-coded unicode locale, a server-configurable unicode locale, etc. since that might allow the spec to standardize on a single interpretation versus specifying the collation to use for a given Cache at creation time.

**Comment by wanderview** [comment]
What do http cache impls do here?

We could probably implement this without too much penalty.  I'd like to see chrome implement it first, though.  There are a number of cache query opts from v1 chrome still hasn't implemented.

**Comment by jakearchibald** [comment]
I don't want to do anything different to the HTTP cache in this regard, but I'm not sure what that is right now.

**Comment by wanderview** [comment]
A quick test in devtools shows that both firefox and chrome:

1. Treat the origin of the URL as case insensitive
2. Treat the path and query as case sensitive

In both browsers (1) seems to be implemented by normalizing the origin to lower case.

**Comment by annevk** [comment]
See the URL parser…

**Comment by jakearchibald** [comment]
Notes:

* Lowercase is tough to define
* There are easy ways to work around this
* We can reopen this if it turns out to be more difficult than we think
