### ISSUE TITLE
Reloading page causes one extra client on client list

### ISSUE THREAD

**Issue by tresdin** [w3c/ServiceWorker#972]
I've placed the below code on SW root for testing `matchAll` with a page reload.
```
clients.matchAll({includeUncontrolled: true, type: 'window'}).then(list => console.log(list)); //2 clients printed, it should be one, right?
```
It output 2 clients while there was only one opening page. The terminated one seem to still be kept on the list. Is that a bug? Or is there any property for indicating a closed one?

**Comment by wanderview** [comment]
I think that's correct today.  We've discussed having separate client IDs for source, target, and replacing clients.  No one has implemented that yet, though.

**Comment by tresdin** [comment]
@wanderview Why don't you add a flag for indicating client states instead? Things like `closed`, 'free', 'controlled', 'ready' or something. This will make the prelisted clients filterable.

**Comment by jungkees** [comment]
The state of the "captured" clients is not dynamic. It reflects the state of the clients of the moment when the `Client` objects are created during the getter methods.

**Comment by tresdin** [comment]
@jungkees I still think a client object should be created only once, and its state better be dynamic.

You can feel free to close this issue though.

**Comment by jakearchibald** [comment]
@tresdin see https://github.com/w3c/ServiceWorker/issues/870#issuecomment-245559217 for the latest proposal.

For your specific case, you'd only match one client if you only have one page open to the origin (and no iframes). With the `includeReserved` `matchAll` option you'll get two clients during navigation.

> I still think a client object should be created only once, and its state better be dynamic.

Since the window state is happening in another thread, having a static lookup for these isn't great. https://github.com/w3c/ServiceWorker/issues/414 for the original API discussion if you're interested.
