### ISSUE TITLE
postMessage keeps service workers alive indefinitely

### ISSUE THREAD

**Issue by mfalken** [w3c/ServiceWorker#980]
Chrome has a bug where a service worker can postMessage to itself to stay alive indefinitely: https://bugs.chromium.org/p/chromium/issues/detail?id=647943

You can also register at two scopes and have those workers ping-pong messages.

I'm wondering if this should be prevented at the spec level, for example:
- postMessage to a service worker that has no in-scope (or same-origin) client won't wake it up, or
- postMessage from a service worker doesn't wake up the destination service worker

If this is an implementation detail, would something heuristic like a SW can be kept alive by at most 5 messages events be reasonable?

**Comment by mattto** [comment]
Workers can also ping-pong each other with fetch() and foreign fetch, so I guess a more general solution is needed.

**Comment by jungkees** [comment]
I think they should be considered abnormal operations, and the user agent should detect and terminate rather than disallowing the usage itself.

**Comment by wanderview** [comment]
"Keeping the worker alive" is a browser implementation detail, no?  The whole grace timer mechanism just falls into the spec's "browser can kill the worker whenever it wants" language.

In FF we currently avoid this by conveniently not setting self.registration.active, etc.  So its impossible to self `postMessage()` right now.  When we implement that, though, I was planning to just inspect the source of the message event.  If it was the same worker that was being posted to, then we would not increment the keep-alive reference count.

**Comment by jakearchibald** [comment]
We decided that background sync can only be called when there's a document open on the origin. This prevents one-off background sync being turned into a periodic sync by recalling sync inside a sync event.

We'll want something similar for background fetch, but it'd be nice to be able to start a download in response to a push message.

I wonder if we can fix all these things with the same mechanism.

When we create an extendable event, we can assign an expiry time to it.

* A fetch event gets an expiry time of x minutes
* A `postMessage` sent by a client with an associated document (so a document or a worker linked to a document) gets an expiry time of x minutes
* A `postMessage` sent by a service worker A to service worker B gets an expiry time equal to the longest expiry time currently holding service worker A open

This means two service workers post messaging each other can only stay alive for a total of 5 minutes.

If we're tagging extendable events like this, we can also say things like "background sync can only be used if the SW is being held open by a push/fetch event".

Too crazy?

**Comment by mattto** [comment]
I think it's OK to call this an implementation detail. I was originally thinking the spec gives room to terminate long-running events, whereas this is a bit different: the browser sees "postMessage" and decides to not postMessage. But you could consider this being the browser terminating the worker just before/during the postMessage call, so it fits under the spec language of termination "at any time".

Jake's is an interesting idea. I may use something like that for the implementation.

**Comment by mkruisselbrink** [comment]
Hah, I just posted the exact same thing @jakearchibald described in the chromium bug for the same issue with regard to foreign fetch ([crbug.com/662443](https://bugs.chromium.org/p/chromium/issues/detail?id=662443)). So yes, I think the solution jake describes makes a lot of sense, when generalized a bit more to apply to any event triggered by another service worker (such as in this case foreign fetch).

Also if in the future we start allowing service workers to start shared and/or dedicated workers, we should make sure that messages/fetches (regular and foreign) made by those workers get the same timeout treatment if a service worker is the only thing holding the worker alive.

**Comment by mkruisselbrink** [comment]
And while I agree that the exact timeout behavior is probably fine as an implementation detail, we should probably at least make sure to mention this issue in the spec somewhere and encourage implementations to put some mitigations in place to prevent it.

**Comment by mkruisselbrink** [comment]
FWIW, Chrome has implemented the timeout behavior described here for message events and foreign fetch events triggered by another service worker.

**Comment by jakearchibald** [comment]
F2F: We should spec this "time passing" behaviour.

**Comment by cchighman** [comment]
Why is it undesirable for a ServiceWorker to remain alive?  Is there a tangible net impact outside of it's suggested implementation ?

**Comment by MarkEmerson** [comment]
Suggested implementation is pretty useless. What can we do in 5 seconds before it dies? Surely if web apps need to run 'like native apps' with all this service worker technology we need the service worker to stay active/alive not keep stopping due to its limited lifespan. We are having to move all our web app code to a android native wrapper and use a webview because the service worker stops running code. Users open up other apps and when the app loses focus, poor old service worker stops. At this rate we may as well just do away with the web app service worker thing altogether. very frustrating. We need code to run in background when the app loses focus otherwise its pointless. there, ive said it.

**Comment by jakearchibald** [comment]
@cchighman 

> Why is it undesirable for a ServiceWorker to remain alive? Is there a tangible net impact outside of it's suggested implementation ?

Privacy & memory usage.

**Comment by MarkEmerson** [comment]
But users request to use our apps and they grant permission so why is privacy an issue? when its granted by the user?. if they wish to revoke permissions let them and all permissions and service workers etc etc can be cleaned up and memory freed. Why is this an issue with web apps? when we are consuming vast amounts of memory with streaming and downloading content more than ever. Who actually complains? the users want to use our apps not be inconvenienced by apps that stop working due to W3C policing how we write apps. its not helping developers its constraining them. just talking here.

**Comment by jakearchibald** [comment]
@MarkEmerson 

> What can we do in 5 seconds

I think you're the first to mention "5 seconds".

> we need the service worker to stay active/alive not keep stopping due to its limited lifespan

We have that with workers & shared workers.

> We are having to move all our web app code to a android native wrapper and use a webview because the service worker stops running code

What kind of work are you trying to do that can't be done in a regular (or shared) worker?

> We need code to run in background when the app loses focus otherwise its pointless

By the way, Android is starting to prevent apps from doing this. It's a big source of battery issues.

For particular long-running processes, you may be interested in https://w3c.github.io/wake-lock/.

**Comment by jakearchibald** [comment]
@MarkEmerson 

> users request to use our apps and they grant permission so why is privacy an issue? 

Service worker isn't behind a permission. Wake lock would be, but presumably it would involve some sort of persistent UI to inform the user that a particular app has a wake lock. This is similar to what recent Android versions do – they use a sticky notification.

> we are consuming vast amounts of memory with streaming and downloading content more than ever.

But that's very visible to the user. We're planning similar visibility with https://github.com/WICG/background-fetch.

> Who actually complains?

Users. They value their privacy and the battery life of their device, especially if these things become broken while the device's screen is off.

**Comment by MarkEmerson** [comment]
great responses - sorry for rant but having all sorts of issues with service worker at present. please tell me if ive missed something. Push API and firebase messages are working dandy but no geo available in service worker is not good for us as users need to use navigation apps and put our app in background. no geo when app loses focus either. we need a heart beat sent to server from client even if the app loses focus. but service worker stops due to its lifespan limitations.  using firebase pings to wake service worker seems  impractical - or is it?.  are we missing anything fundamental here? can we achieve all of the above with shared workers? without the service worker stopping and when the app loses focus?

**Comment by MarkEmerson** [comment]
just reading some of the W3org discussions about service workers and background location etc. when i see comments on W3org like this: > 'Tracking the user in the background is highly likely to be a case of a site acting poorly'.  According to who? who makes these assumptions on behalf of both user and developer?

**Comment by jakearchibald** [comment]
> using firebase pings to wake service worker seems impractical

Yeah, you have to show a notification as the result of a push. Again, we want this background work to be user-visible.

> need to use navigation apps and put our app in background

It feels like https://w3c.github.io/wake-lock/ is what you're looking for. You want a CPU lock on the tab, maybe a screen lock too (if you're showing position on maps).

> can we achieve all of the above with shared workers? without the service worker stopping and when the app loses focus?

Unfortunately not. Shared workers will be killed once their parent page is killed.

> 'Tracking the user in the background is highly likely to be a case of a site acting poorly'. According to who?

You don't have to search too hard to find angry articles like this https://www.theverge.com/2016/11/30/13763714/uber-location-data-tracking-app-privacy-ios-android. People generally don't like being spied on.

You may also be interested in https://techcrunch.com/2014/04/04/the-right-way-to-ask-users-for-ios-permissions/, which goes into some detail on permissions. It's difficult getting the balance right. You want powerful features, but you want to make sure the user is aware (continually if necessary) they're being used.

**Comment by MarkEmerson** [comment]
Agreed, the balance between usability, privacy and trust is the challenge. So the takeaway is: a web app will not support background tasks at present or near future. Id rather not move our web app code to our android wrapper but looks like we have no choice now. Thanks again Jake for all your invaluable feedback, references and advice. Mark

**Comment by jakearchibald** [comment]
I think https://w3c.github.io/wake-lock/ gives us a way forward that balances the needs of background processing & keeping the user informed. But yeah, if you need to ship this year, a native wrapper will do it. Like I said, Android is cracking down on background work, so be careful you don't end up with the same problems there.

**Comment by jungkees** [comment]
@wanderview, Chrome implemented the behavior in https://github.com/w3c/ServiceWorker/issues/980#issuecomment-248920422: https://codereview.chromium.org/2506263005. I'd like to check with you before spec'ing this if Firefox will implement the same.

**Comment by wanderview** [comment]
Is https://github.com/w3c/ServiceWorker/issues/980#issuecomment-248920422 really what was implemented?  I've been told that chrome will not kill a service worker if there is a controlled Client open.  These timers are only applied on "background" service workers without any Client.  That doesn't seem to be completely expressed in that comment.

**Comment by mattto** [comment]
Chrome certainly kills service workers (that sounds so wrong) with a controlled Client open. It's done that since the early implementation.

We implemented the basic idea of https://github.com/w3c/ServiceWorker/issues/980#issuecomment-248920422. Each running service worker has a "max timeout" computed as the longest timeout of all its requests, and when a new message or foreign fetch request arrives, its timeout of the new request is clamped to the max timeout of the originating service worker, so it can't extend the overall lifetime beyond the originating worker's.

**Comment by wanderview** [comment]
What about if there is a fetch event?  @jakearchibald suggested to me these should have infinite lifetime as long as the client exists in order to support playing long videos, etc.

**Comment by mattto** [comment]
Our implementation still kills the worker in this case. The behavior probably should change in the future. There's an open bug about it: https://bugs.chromium.org/p/chromium/issues/detail?id=678798

**Comment by wanderview** [comment]
I guess I would be happy to see the spec say something like:

1. The service worker has a `lifetime budget`.  When the budget is exhausted the service worker is killed even if there are pending extension promises.
2. The `lifetime budget` is updated per https://github.com/w3c/ServiceWorker/issues/980#issuecomment-248920422
3. The `lifetime budget` may also be dependent on the existence of a controlled client.  For example, if a FetchEvent grants a large/infinite budget, but then the user closes the requesting window, then the SW should have that infinite budget reduced.

We can leave the exact budget values as an implementation detail for now since it seems some tuning is still happening.

**Comment by jungkees** [comment]
> @jakearchibald suggested to me these should have infinite lifetime as long as the client exists in order to support playing long videos, etc.

> The lifetime budget may also be dependent on the existence of a controlled client.

I think https://github.com/WICG/background-fetch#playing-a-podcast-as-its-background-fetching would solve the issue posed in https://bugs.chromium.org/p/chromium/issues/detail?id=678798. That considered, I think we better keep the hard `lifetime budget` to be in favor of battery usage and to not allow maliciously written service workers.

**Comment by valioDOTch** [comment]
Apart from the battery issue, it might become a an overall performance issue, if there's no lifetime budget.

We do not want services like Coinhive getting tied to service workers, without users being notified about it.

**Comment by jimmywarting** [comment]
There are [good usecases](https://github.com/w3c/webrtc-pc/pull/317#issuecomment-170610532) too with having long running service worker. Service worker are better then SharedWorker if it were not for the short lifetime. in a since that it can handle FetchEvent. Stay alive durning reload, do backgroundFetch, push, sync and much more.

i think the short lifetime is stupid and it will only make developer do this kind of hack, clearly there are good usecases for having long lived service worker too. developers have asked for long lived service worker many times. This is one of those things that would make you develop a Native app instead of a PWA, which is sad. 

but if we are worried about things like Coinhive, can't browser then instead help to defeat them with a prompt saying something like

> "example.com" is running a high CPU intensive Service worker" or 
> "example.com" have been running a worker for more then 20 minutes"
>
> `[kill it]` `[block it]` `[keep it alive]`

Developer would do good by trying to avoid those message from ever poping up.
another acceptable solution would be to ask for permission.

```js
navigator.permissions.request({name: 'long-lived-sw'})
```

WebTorrent, IPFS. PeerCloud, Webtorrent, PeerCDN, StreamRoot, and Peer5 would all benefit from having WebRTC in service worker and run for longer period of time.

**Comment by jakearchibald** [comment]
> I _almost_ think the hole backgroundFetch was unnecessary first and could have been avoided by other means if you only let us keep the service worker alive for longer.

This would be a battery drain and a privacy issue. Messages don't help while the phone is in the user's pocket.

> Or don't show this messages, just kill it when the user have closed all tabs

That wouldn't be very 'background'.

**Comment by jakearchibald** [comment]
We're not going to allow a service worker to run indefinitely. Features that require some form of persistence should be handed off to the OS somehow, with a way for the origin to collect the data later (like how background fetch works).

Closing this in favour of https://github.com/w3c/ServiceWorker/issues/1566 which covers how to spec expiry.

**Comment by gustavopch** [comment]
@jakearchibald I'm new to service workers, so I may be making some false assumptions, but it seems to me that being able to have the service worker live while tabs are open would be a huge step in the direction of simplifying web development with MPAs. I mean, sometimes you need to have some stuff that keeps running for as long as the page is open, like web sockets, and, currently, AFAIK that can only be accomplished with SPAs. So why not let service workers fill that gap? Web development is so much easier with MPAs.
